name: rovix
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  connectivity_plus: ^7.1.1
  flutter_dotenv: ^6.0.1
  flutter_screenutil: ^5.9.3
  firebase_core: ^4.9.0
  animate_do: ^4.2.0
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.3

  freezed_annotation: null
  equatable: ^2.0.8
  get_it: ^9.2.1

  dio: ^5.8.0+1
  retrofit: ">=4.7.2 <4.9.0"
  pretty_dio_logger: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  very_good_analysis: ^9.0.0

  build_runner: null
  retrofit_generator: "<10.1.2"
  json_serializable: null
  freezed: null

  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - .env.dev
    - .env.prod
    - assets/images/
    - assets/images/admin/
    - assets/images/core/
    - assets/images/customer/
    - assets/svg/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/arabic/cairo/Cairo-Bold.ttf
          weight: 700

        - asset: assets/fonts/arabic/cairo/Cairo-Medium.ttf
          weight: 500

        - asset: assets/fonts/arabic/cairo/Cairo-Regular.ttf
          weight: 400

    - family: Poppins
      fonts:
        - asset: assets/fonts/english/poppins/Poppins-Bold.ttf
          weight: 700

        - asset: assets/fonts/english/poppins/Poppins-Medium.ttf
          weight: 500

        - asset: assets/fonts/english/poppins/Poppins-Regular.ttf
          weight: 400

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/launch_icon.png

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/launch_icon.png

  android_12:
    color: "#FFFFFF"
    image: assets/images/launch_icon.png

flutter_intl:
  enabled: true
