// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFuvoRAyEBy8k35Dkwa9Refjdc1Agp2pQ',
    appId: '1:381082097744:web:b5e86a811128284719d955',
    messagingSenderId: '381082097744',
    projectId: 'rovix-store-app',
    authDomain: 'rovix-store-app.firebaseapp.com',
    storageBucket: 'rovix-store-app.firebasestorage.app',
    measurementId: 'G-VY3G5NKPJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_UcCWAr1jlKpF6utbgaYJIX2xRH0oHs0',
    appId: '1:381082097744:android:9e5929b70cd784c519d955',
    messagingSenderId: '381082097744',
    projectId: 'rovix-store-app',
    storageBucket: 'rovix-store-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI7zra1ejPGdVspEmFmIY4yvQyZ3dnG-s',
    appId: '1:381082097744:ios:27a1e2426e6fe4f719d955',
    messagingSenderId: '381082097744',
    projectId: 'rovix-store-app',
    storageBucket: 'rovix-store-app.firebasestorage.app',
    iosBundleId: 'com.example.rovix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI7zra1ejPGdVspEmFmIY4yvQyZ3dnG-s',
    appId: '1:381082097744:ios:27a1e2426e6fe4f719d955',
    messagingSenderId: '381082097744',
    projectId: 'rovix-store-app',
    storageBucket: 'rovix-store-app.firebasestorage.app',
    iosBundleId: 'com.example.rovix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFuvoRAyEBy8k35Dkwa9Refjdc1Agp2pQ',
    appId: '1:381082097744:web:607d8ca9d9387ed219d955',
    messagingSenderId: '381082097744',
    projectId: 'rovix-store-app',
    authDomain: 'rovix-store-app.firebaseapp.com',
    storageBucket: 'rovix-store-app.firebasestorage.app',
    measurementId: 'G-3T26STJE82',
  );
}
